[template]
cargo_generate_version = ">=0.10.0"

[placeholders.authors]
type = "string"
prompt = "Authors?"

[placeholders.gh-username]
type = "string"
prompt = "GitHub username (or organization)?"
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,37}[A-Za-z0-9]$"

[placeholders.project-description]
type = "string"
prompt = "Project description?"

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs", ".envrc.example", "tests/test_utils.rs"]

[conditional.'crate_type == "bin"']
ignore = ["src/lib.rs"]
